{{- if .Values.config.database.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.database.host }}-deploy
  labels:
  {{- include "sregistry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- include "sregistry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "sregistry.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Values.config.database.name }}
        securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.config.database.name }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
        - name:  POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        ports:
        - name: postgres
          containerPort: {{ .Values.config.database.port }}
          protocol: TCP
        resources:
        {{- toYaml .Values.config.database.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
