{{- if .Values.config.database.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.database.host }}
  labels:
  {{- include "sregistry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
  {{- include "sregistry.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.config.database.port }}
    targetPort: postgres
    name: postgres
{{- end }}
