apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
  {{- include "sregistry.labels" . | nindent 4 }}
  {{- if .Values.images.nginx.annotations }}
  annotations:
  {{- toYaml .Values.images.nginx.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.images.nginx.type }}
  selector:
  {{- include "sregistry.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.images.nginx.port }}
    targetPort: nginx
    name: nginx
