apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
  {{- include "sregistry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.config.nginx.type }}
  selector:
  {{- include "sregistry.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.config.nginx.port }}
    targetPort: nginx
    name: nginx
