{{- if .Values.config.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
  {{- include "sregistry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- include "sregistry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "sregistry.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: redis
        securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.config.redis.image }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        ports:
        - name: redis
          containerPort: {{ .Values.config.redis.port }}
          protocol: TCP
        resources:
        {{- toYaml .Values.config.redis.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
