apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.uwsgi.host }}
  labels:
  {{- include "sregistry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
  {{- include "sregistry.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.config.uwsgi.port }}
    targetPort: uwsgi
    name: uwsgi
