apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sregistry-sts
  labels:
  {{- include "sregistry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.images.replicaCount }}
  selector:
    matchLabels:
    {{- include "sregistry.selectorLabels" . | nindent 6 }}
  serviceName: "uwsgi"
  {{- include "sregistry.claimTemplate" .Values.persistence | nindent 2 }}
  template:
    metadata:
      labels:
      {{- include "sregistry.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- include "sregistry.customVolumes" . | nindent 6 }}
      - name: shub-vol
        configMap:
          name: shub-config
      - name: nginx-vol
        configMap:
          name: nginx-config
      containers:
      - name: uwsgi
        securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ .Values.images.sregistry.image | quote }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        {{- include "sregistry.env" . | nindent 8 }}
        {{- include "sregistry.mounts" .Values.auth.customPlugins | nindent 8 }}
        ports:
        - name: uwsgi
          containerPort: {{ .Values.images.sregistry.port }}
      - name: worker
        image: {{ .Values.images.sregistry.image | quote }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        {{- include "sregistry.env" . | nindent 8 }}
        {{- include "sregistry.mounts" .Values.auth.customPlugins | nindent 8 }}
        command: [ "python", "/code/manage.py", "rqworker", "default" ]
      - name: scheduler
        image: {{ .Values.images.sregistry.image | quote }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        {{- include "sregistry.env" . | nindent 8 }}
        {{- include "sregistry.mounts" .Values.auth.customPlugins | nindent 8 }}
        command: [ "python", "/code/manage.py", "rqscheduler" ]
      - name: nginx
        image: {{ .Values.images.nginx.image | quote }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        {{- include "sregistry.mounts" .Values.auth.customPlugins | nindent 8 }}
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          name: nginx-vol
        - mountPath: /etc/nginx/uwsgi_params.par
          subPath: uwsgi_params.par
          name: shub-vol
        ports:
        - name: nginx
          containerPort: {{ .Values.images.nginx.port }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
